services:
  xampp:
    image: tomsik68/xampp:latest
    container_name: ch9-db-server
    privileged: true
    ports:
      - "8088:80"
    volumes:
      - /workspaces/302-app-dev/chapter09:/opt/lampp/htdocs/chapter09:Z  ## รันบน GithubWorkspace
    restart: unless-stopped